#!/bin/bash

server="$(zenity --entry)"
#if [ -n "$server" ]
#then
#	mkdir -p ${HOME}/screenshot/"$server"
#	
#	xwd | xwdtopnm | pnmtojpeg >${HOME}/screenshot/"$server"/screenshot-$$.jpg
#	#xwd -root -out ${HOME}/screenshot-$$ | xwdtopnm ${HOME}/screenshot-$$ | pnmtojpeg >${HOME}/screenshot/$server/screenshot-$$.jpg
#fi
dir="$(dirname "${server}")"
file="$(basename "${server}")"
echo "${dir} : ${file}"
mkdir -p ~/screenshot/"${dir}"
scrot -q 100 -s ~/screenshot/"${dir}"/"${file}-%Y-%m-%d_%H-%M.png"
